const DIFFICULTY = 4;   //DIFFICULTYの初期値
const MINE_RATE = 3000; //DIFFICULTYを動的に変化させるためのレート
const INITIAL_BALANCE = 500; //残高初期値
const MINING_REWARD = 50;


module.exports = {DIFFICULTY, MINE_RATE, INITIAL_BALANCE, MINING_REWARD};  //DIFFICULTYをexports
